---
title: "College Campuses"
author: "Emma Livingston"
date: "4/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(broom)
```

```{r}
college_campuses <- read_csv(here("/data/Smith_Capstone_College_Campus.csv"))
unique_matched <- read_csv(here("/data/Smith_Capstone_Voters_Unique.csv"))
college_demographics <- read_csv(here("/data/college_demographics.csv"))
additional_vars <- read_csv(here("/data/Smith_Capstone_Additional_Voter_File_Vars.csv"))
```

```{r}
codes_to_keep <- c(4600748,
  4600752,
  4600785,
  4598681,
  4616686,
  4600760,
  4600781,
  4600756,
  4600775,
  4600761,
  4600779,
  4600766,
  4600767,
  4600776,
  4600783,
  4600768,
  4598682,
  4600770,
  4600782,
  #4587626, pledge to vote
  4600771,
  4600754,
  4600757,
  4600758,
  4600778,
  4598678,
  4600769,
  4598684,
  4600786,
  4600777,
  4598680,
  4600755,
  4646492,
  4600780,
  4616703,
  4600750,
  4600759,
  4600784)

```

```{r}
matched_w_campuses <- unique_matched %>%
  select(-contains("activistcode")) %>%
  left_join(select(college_campuses, vanid, activistcodeid, activistcodename), by = "vanid") %>%
  filter(activistcodeid %in% codes_to_keep) 
full_data <- matched_w_campuses %>%
  left_join(select(additional_vars, van_id, vb_voterbase_race:tb_income_range_prem_cd), by = c("vanid" = "van_id"))
```



```{r}
full_data$vb_voterbase_race <- recode(full_data$vb_voterbase_race, "Caucasian" = "White_Count")
full_data$vb_voterbase_race <- recode(full_data$vb_voterbase_race, "Uncoded" = "Unknown_Count")
full_data$vb_voterbase_race <- recode(full_data$vb_voterbase_race, "Other" = "POC_Count")
full_data$vb_voterbase_race <- recode(full_data$vb_voterbase_race, "African-American" = "POC_Count")
full_data$vb_voterbase_race <- recode(full_data$vb_voterbase_race, "Asian" = "POC_Count")
full_data$vb_voterbase_race <- recode(full_data$vb_voterbase_race, "Hispanic" = "POC_Count")
full_data$vb_voterbase_race <- recode(full_data$vb_voterbase_race, "Native American" = "POC_Count")

clean_data <- full_data %>% 
  select(van_id, activistcodeid, activistcodename, vb_voterbase_race)%>%
  filter(activistcodeid %in% codes_to_keep)%>%
  mutate(vb_voterbase_race = replace_na(vb_voterbase_race, "Unknown_Count"))

counts <- clean_data %>%
  group_by(activistcodename, vb_voterbase_race)%>%
  count(vb_voterbase_race)%>%
  spread(vb_voterbase_race, n)
```

```{r}
# Expected proportions for each college
clean_college_dems <- college_demographics %>%
  select(activistcodename, nonresident_alien,	unknown_race,	two_or_more_races,	white,	native_hawaiian_or_other_pac_islander,	hispanic,	black_or_african_american,	asian,	american_indian_or_alaska_native, Total_Pop)%>%
  mutate(unknown = nonresident_alien + unknown_race + two_or_more_races) %>% 
  mutate(POC = native_hawaiian_or_other_pac_islander + hispanic + black_or_african_american + asian + american_indian_or_alaska_native)%>%
  select(activistcodename, white, unknown, POC, Total_Pop)
```

```{r}
counts_and_expected <- counts %>%
  inner_join(clean_college_dems, by = "activistcodename")%>%
  mutate(POC_Count = replace_na(POC_Count, 0))%>%
  mutate(Unknown_Count = replace_na(Unknown_Count, 0))%>%
  mutate(Prop_POC_Expected = (POC/100))%>%
  mutate(Prop_White_Expected = (white/100))%>%
  mutate(Prop_Unknown_Expected = (unknown/100))%>%
  select(activistcodename, POC_Count, White_Count, Unknown_Count, Prop_POC_Expected, Prop_White_Expected, Prop_Unknown_Expected)%>%
  mutate(sum_prop = (Prop_POC_Expected + Prop_White_Expected + Prop_Unknown_Expected)) #%>% #fix this
  #filter(sum_prop == 1) #fix this
View(counts_and_expected)
```

```{r}
# for (i in counts_and_expected) {
#   counts <- c(counts_and_expected$POC_Count, counts_and_expected$White_Count, counts_and_expected$Unknown_Count)
#   p <- c(counts_and_expected$Prop_POC_Expected, counts_and_expected$Prop_White_Expected, counts_and_expected$Prop_Unknown_Expected)
# res <- chisq.test(counts, p)
# print(res)
# }
#problem because some expected values are too low
```

```{r}
#need a dataset with state and college_type
test_data <- counts_and_expected %>%
  inner_join(college_demographics, by = "activistcodename") %>%
  #Need actual proportions for visualizations
  mutate(Prop_POC_Actual = POC_Count / (POC_Count+White_Count+Unknown_Count),
         Prop_White_Actual = White_Count / (POC_Count+White_Count+Unknown_Count),
         Prop_Unknown_Actual = Unknown_Count / (POC_Count+White_Count+Unknown_Count))
  
#see how many of each college type each state has
test_data %>%
  group_by(state, college_type) %>%
  count()

#find total counts of campaigned people in each college
test_data <- test_data %>%
  mutate(total_count = POC_Count + White_Count + Unknown_Count,
  expected_POC_count = total_count * Prop_POC_Expected,
  expected_White_count = total_count * Prop_White_Expected,
  expected_Unknown_count = total_count * Prop_Unknown_Expected)

#Find which colleges have expected count < 5
colleges_to_group <- test_data %>%
  filter(expected_POC_count < 5 | expected_White_count < 5 | expected_Unknown_count < 5)
```

```{r}
#turn off scientific notation
options(scipen = 999)

#test chi_squared
results <- test_data %>%
  do(tidy(chisq.test(
    c(.$POC_Count, .$White_Count, .$Unknown_Count),
    p = c(
      .$Prop_POC_Expected,
      .$Prop_White_Expected,
      .$Prop_Unknown_Expected
    )
  )))
View(results)

#just basic college info to join with
college_info <- test_data %>%
  select(activistcodename, state, college_type)

#View all chi squared tests
results <- results %>%
  inner_join(college_info, by = "activistcodename") %>%
  select(-c(parameter, method))
View(results)
```


```{r}
#tidy
for_viz <- test_data %>%
  select(
    activistcodename,
    college_type,
    state,
    Prop_POC_Expected,
    Prop_White_Expected,
    Prop_Unknown_Expected,
    Prop_POC_Actual,
    Prop_White_Actual,
    Prop_Unknown_Actual
  ) %>%
  pivot_longer(
    c(
      Prop_POC_Expected,
      Prop_White_Expected,
      Prop_Unknown_Expected,
      Prop_POC_Actual,
      Prop_White_Actual,
      Prop_Unknown_Actual
    ),
    names_to = "case",
    values_to = "proportion"
  ) %>%
  separate(case, into = c("prop", "race", "value"), sep = "_") %>%
  select(-c(prop))

#plot
ggplot(for_viz, 
       aes(x = race, 
           y = proportion, 
           fill = value)) + 
  geom_bar(stat = "identity", 
           position = "dodge")  +
  facet_wrap(~college_type)

#BY STATE:
ggplot(for_viz, 
       aes(x = race, 
           y = proportion, 
           fill = value)) + 
  geom_bar(stat = "identity", 
           position = "dodge") + 
  facet_wrap(state~college_type)

#Just NH
ggplot(filter(for_viz, state == "NH"),
       aes(x = race, y = proportion, fill = value)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~ college_type) +
  ggtitle("New Hampshire")

#Just IA
ggplot(filter(for_viz, state == "IA"),
       aes(x = race, y = proportion, fill = value)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~ college_type) +
  ggtitle("Iowa")

#Just PA
ggplot(filter(for_viz, state == "PA"),
       aes(x = race, y = proportion, fill = value)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~ college_type) +
  ggtitle("Pennsylvania")

#Without colleges with too small of expected counts
for_viz_2 <- for_viz %>%
  anti_join(colleges_to_group, by = "activistcodename")

ggplot(for_viz_2, 
       aes(x = race, 
           y = proportion, 
           fill = value)) + 
  geom_bar(stat = "identity", 
           position = "dodge") + 
  facet_wrap(state~college_type)

#see how many of each type of college per state is left after removed the ones not possible
#to run a chi-squared test on
# for_viz_2 %>%
#   group_by(state, college_type) %>%
#   count()
```

```{r}
#visualizing only the ones unable to run tests on
for_viz_3 <- for_viz %>%
  inner_join(colleges_to_group, by = "activistcodename")

ggplot(for_viz_3, 
       aes(x = race, 
           y = proportion, 
           fill = value)) + 
  geom_bar(stat = "identity", 
           position = "dodge") + 
  facet_wrap(~activistcodename)
```

```{r}
#combine NH community colleges that we couldn't run individual tests on

#Get summed actual counts
NH_test_data <- test_data %>%
  filter(activistcodename %in% c("Great Bay CommColleg", "Manchester CommColle", "NHTI")) %>%
  mutate(sum_POC_count = sum(NH_test_data$POC_Count),
         sum_White_count = sum(NH_test_data$White_Count),
         sum_Unknown_count = sum(NH_test_data$Unknown_Count))

#Get expected counts for colleges
expected_counts <- clean_college_dems %>%
  mutate(white_counts = Total_Pop * (white/100))%>%
  mutate(unknown_counts = Total_Pop * (unknown/100))%>%
  mutate(POC_counts = Total_Pop * (POC/100))

#Select colleges and sum counts for grouping
NH_data <- expected_counts %>%
  filter(activistcodename %in% c("Great Bay CommColleg", "Manchester CommColle", "NHTI")) %>%
  mutate(NH_total = sum(Total_Pop),
         NH_white_counts = sum(white_counts),
         NH_POC_counts = sum(POC_counts),
         NH_Unknown_counts = sum(unknown_counts),
         NH_expected_white_Prop = NH_white_counts / NH_total,
         NH_expected_POC_Prop = NH_POC_counts / NH_total,
         NH_expected_Unknown_Prop = NH_Unknown_counts / NH_total)

NH_data[1, 1] <- "combined_NH_2yr_coll"

NH_data <- NH_data %>%
  filter(activistcodename == "combined_NH_2yr_coll") %>%
  select(activistcodename, contains("NH")) %>%
  #add in summed actual counts found from NH_test_data
  mutate(actual_POC_count = 3,
         actual_white_count = 50,
         actual_unknown_count = 4)

#run chi squared test
results_NH <- NH_data %>%
  do(tidy(chisq.test(
    c(.$actual_POC_count, .$actual_white_count, .$actual_unknown_count),
    p = c(
      .$NH_expected_POC_Prop,
      .$NH_expected_white_Prop,
      .$NH_expected_Unknown_Prop
    )
  )))
View(results_NH)
#insignificant results

#Clean data to visualize results
#create actual proportions
NH_data <- NH_data %>%
  mutate(total_count = actual_POC_count + actual_white_count + actual_unknown_count,
         NH_actual_POC_prop = actual_POC_count / total_count,
         NH_actual_white_prop = actual_white_count / total_count,
         NH_actual_Unknown_prop = actual_unknown_count / total_count)

#tidy
for_viz_NH <- NH_data %>%
  pivot_longer(
    c(
      NH_expected_white_Prop,
      NH_expected_POC_Prop,
      NH_expected_Unknown_Prop,
      NH_actual_POC_prop,
      NH_actual_white_prop,
      NH_actual_Unknown_prop
    ),
    names_to = "case",
    values_to = "proportion"
  ) %>%
  separate(case, into = c("NH", "case", "race", "value"), sep = "_") %>%
  select(activistcodename, case, race, proportion)

#visualize
ggplot(for_viz_NH, 
       aes(x = race, 
           y = proportion, 
           fill = case)) + 
  geom_bar(stat = "identity", 
           position = "dodge") +
  ggtitle("grouped Great Bay CommColleg, Manchester CommColle, NHTI")
```


## Case Study

```{r}
case_study_df <- test_data %>% 
  select(activistcodename, contains("_Count"), state, college_type, Total_Pop, out_of_state) 


case_study_df %>%
  select(activistcodename, state, college_type, total_count, Total_Pop, out_of_state) %>%
  arrange(state, desc(total_count)) %>%
  View()


snu <- full_data %>%
  filter(activistcodeid == 4600786) %>%
  group_by(vb_vf_source_state) %>%
  tally() %>%
  arrange(desc(n))

sum(snu$n) - 91

#77 out of state students reached at SNU


case_study <- function(college_act_id) {
  a <- full_data %>%
    filter(activistcodeid == college_act_id) %>%
    group_by(vb_vf_source_state) %>%
    tally() %>%
    arrange(desc(n))
  return(a)
}

#southern new hampshire university
snu <- case_study(4600786)
snu

#new england college 78% out of state, 	2521 students
nec <- case_study(4600783)
nec
sum(nec$n) - nec$n[1]
#102 people targeted, only 27 were registered to vote in NH! they got 75 out of state people

#university of nh manchester, 4% out of state
unhm <- case_study(4600778)
unhm
sum(unhm$n) - unhm$n[1]
#out of 58 people, they had 20 people out of state

#great bay community college, 6% out of state, 1887 students
gbcc <- case_study(4600766)
gbcc
#all were from NH! granted this is a small sample size, but 

#nhti 3% out of state, 	3478 students, 42 reached
nhti <- case_study(4600768)
nhti
sum(nhti$n) - nhti$n[1]
#only 5 out of state
```








