---
title: "in_out_state"
author: "Sophia Foster"
date: "5/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

```{r}
#read data
college_demographics <- read_csv(here("/data/college_demographics.csv"))
```

```{r}
#create variable with percent of total students from in state
college_dems_in_state <- college_demographics %>%
  rename(foreign_countries = "foreign countries") %>%
  mutate(percent_in = (100*in_state) / (in_state + out_of_state + foreign_countries + unknown_residence))%>%
  drop_na(state, in_state)

#relevel college types
college_dems_in_state$college_type <- factor(college_dems_in_state$college_type, levels = c("Public, 2-year", "Public, 4-year or above", "Private not-for-profit, 4-year or above"))

#rename college type for graph
college_dems_in_state$college_type <-recode(college_dems_in_state$college_type, "Private not-for-profit, 4-year or above" = "Private, 4-Year or above")
```

```{r}
#create bar graph
ggplot(college_dems_in_state, 
       aes(x = college_type, 
           y = percent_in,
           fill = college_type)) + 
  geom_bar(stat = "identity", 
           position = "dodge") +
  scale_fill_manual(values = c("#be3a34", "#004f71", "#465a01")) +
  facet_wrap(~state)+
  theme(axis.text.x = element_blank(), plot.title = element_text(size = 24), axis.title=element_text(size=18), legend.text=element_text(size=16), legend.title=element_text(size=18))+
  labs(title="In-State Students by College Type and State", fill = "College Type")+
  xlab("College Type")+
  ylab("% of Students")

```

